todo_project/todoproject/todoapp/urls.py
from django.urls import path
from . import views
app_name = 'todoapp'

urlpatterns = [
    path('',views.index,name='index'),
    path('delete/<int:taskid>/',views.delete,name='delete'),
    path('update/<int:id>/',views.update,name='update'),
    path('tlhome/',views.TaskList.as_view(),name='tlhome'),
    path('tldetail/<int:pk>/',views.TaskDetailView.as_view(),name='tldetail'),
    path('tlupdate/<int:pk>/',views.TaskUpdateView.as_view(),name='tlupdate'),
    path('tldelete/<int:pk>/',views.TaskDeleteView.as_view(),name='tldelete'),

]

todo_project/todoproject/todoproject/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('todoapp.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                            document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                            document_root=settings.MEDIA_ROOT)   

todo_project/todoproject/todoapp/models.py
from django.db import models
from django.shortcuts import redirect, render


# Create your models here.

class Task(models.Model):   
        name = models.CharField(max_length=250)
        priority = models.IntegerField()
        date = models.DateField()
        def __str__(self):
            return self.name
    

todo_project/todoproject/todoapp/forms.py
from dataclasses import fields
from .models import Task
from django import forms


class TodoForm(forms.ModelForm):
    class Meta:
        model=Task
        fields=['name','priority','date']

todo_project/todoproject/todoapp/views.py
from pyexpat import model
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.template import context
from django.urls import reverse_lazy
from .models import Task
from .forms import TodoForm
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import UpdateView,DeleteView
# Create your views here.

class TaskList(ListView):
    model = Task
    template_name = 'home.html'
    context_object_name = 'task1'

class TaskDetailView(DetailView):
    model = Task
    template_name = 'detail.html'
    context_object_name = 'task'    

class TaskUpdateView(UpdateView):
    model = Task
    template_name = 'update.html'
    context_object_name = 'task'
    fields = ('name','priority','date')

def get_success_url(self):
    return reverse_lazy('tldetail',kwargs={'pk':self.object.id})

class TaskDeleteView(DeleteView):
    model = Task
    template_name = 'delete.html'
    success_url = reverse_lazy('tlhome/')  

def index(request):
    task1 = Task.objects.all()
    if request.method == 'POST':
        name = request.POST.get('name','')
        priority = request.POST.get('priority','')
        priority = request.POST.get('priority','')
        date = request.POST.get('date','')
        task=Task(name=name,priority=priority,date=date)
        task.save()

    return render(request,'home.html',{'task1':task1})

def delete(request,taskid):
    task = Task.objects.get(id=taskid)
    if request.method == 'POST':
        task.delete()
        return redirect('/')
    return render(request,'delete.html')    
        
def update(request,id):
    task = Task.objects.get(id=id)
    fm = TodoForm(request.POST or None,instance=task)
    if fm.is_valid():
        fm.save()
        return redirect('/')
    return render(request,'edit.html',{'fm':fm,'task':task})    

todo_project/todoproject/templates/base.html
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title></title>
</head>
<body>
    {% block content %}

    {% endblock %}
</body>
</html>

todo_project/todoproject/templates/delete.html
{% extends 'base.html' %}

{% block content %}

<form method="POST">
    {% csrf_token %}
    <p>Did you done this work?</p>
    <button type="submit" class="btn btn-danger">Yes</button>
</form>


{% endblock %}

todo_project/todoproject/templates/detail.html
{% extends 'base.html' %}

{% block content %}

<div class="container p-5">
<div class="card mb-3 shadow">
    <div class="card-body">
        <h4 class="card-title">{{task.name}}</h4>
        <p>{{task.priority}}</p>
        <p>{{task.date}}</p>
        <a href="{% url 'todoapp:delete' task.id %}" class="btn btn-danger">Done</a>
        <a href="{% url 'todoapp:update' task.id %}" class="btn btn-warning">Update</a>
    </div>
</div>
</div>


{% endblock %}

todo_project/todoproject/templates/edit.html
{% extends 'base.html' %}

{% block content %}
<div class="container pt-5">
<form method="POST">
    {% csrf_token %}
    
        {{fm.as_p}}
    <button type="submit" class="btn btn-danger">Confirm</button>
</form>
</div>
{% endblock %}

todo_project/todoproject/templates/home.html
{% extends 'base.html' %}

{% block content %}
<div class="container-fluid">
    <div class="banner bg-primary">
        <div class="banner-text pt-5">
            <h2>TODO</h2>
        </div>
    </div>
</div>
<div class="container pt-5">
    <div class="row">
        <div class="col-md-6">
            <form method="POST" class="p-5 shadow">
                {% csrf_token %}
                <div class="mb-3 col-md-6 form-group">
                    <label class="form-label">Task</label>
                    <input
                        type="text"
                        name="name"
                        class="form-control"
                        placeholder="Enter task"
                    >
                </div>
                <div class="mb-3 col-md-6 form-group">
                    <label class="form-label">Priority</label>
                    <input
                        type="text"
                        name="priority"
                        class="form-control"
                        placeholder="Enter priority"
                    >
                </div>
                <div class="mb-3 col-md-6 form-group">
                    <label class="form-label">Date</label>
                    <input
                        type="date"
                        name="date"
                        class="form-control"
                    >
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
        <div class="col-md-6">
            {% for i in task1 %}
            <div class="card mb-3 shadow">
                <div class="card-body">
                    <h4 class="card-title">{{i.name}}</h4>
                    <p>{{i.priority}}</p>
                    <p>{{i.date}}</p>
                    <a href="{% url 'todoapp:delete' i.id %}" class="btn btn-danger">Done</a>
                    <a href="{% url 'todoapp:update' i.id %}" class="btn btn-warning">Update</a>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

todo_project/todoproject/templates/update.html
{% extends 'base.html' %}

{% block content %}
<div class="card">
    <div class="card-header">
        <div class="card-title">
            Update
        </div>
        <div class="card-body">
            <form method="POST">
                {% csrf_token %}
                {{f.as_p}}
                <button type="submit" class="btn btn-danger">Confirm</button>
            </form>
        </div>
    </div>
</div>

{% endblock %}